package com.paypal.donation.models;
// Generated Feb 23, 2012 2:26:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * RenderLocation generated by hbm2java
 */
public class RenderLocation implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String payerid;
	private String country;
	private String ipaddress;
	private String host;
	private String locale;
	private String language;
	private Date createdDt;
	private String widgetexternalid;
	private double amount;
	private Character donateflag;

	public RenderLocation() {
	}

	public RenderLocation(Date createdDt, String widgetexternalid,
			double amount, Character donateflag) {
		this.createdDt = createdDt;
		this.widgetexternalid = widgetexternalid;
		this.amount = amount;
		this.donateflag = donateflag;
	}

	public RenderLocation(String payerid, String country, String ipaddress,
			String host, String locale, String language, Date createdDt,
			String widgetexternalid, double amount, Character donateflag) {
		this.payerid = payerid;
		this.country = country;
		this.ipaddress = ipaddress;
		this.host = host;
		this.locale = locale;
		this.language = language;
		this.createdDt = createdDt;
		this.widgetexternalid = widgetexternalid;
		this.amount = amount;
		this.donateflag = donateflag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPayerid() {
		return this.payerid;
	}

	public void setPayerid(String payerid) {
		this.payerid = payerid;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	public String getWidgetexternalid() {
		return this.widgetexternalid;
	}

	public void setWidgetexternalid(String widgetexternalid) {
		this.widgetexternalid = widgetexternalid;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public Character getDonateflag() {
		return this.donateflag;
	}

	public void setDonateflag(Character donateflag) {
		this.donateflag = donateflag;
	}

}
