package com.paypal.donation.models;

// Generated Dec 9, 2011 10:53:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Widget generated by hbm2java
 */
public class Widget implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String payerid;
	private String widgetexternalid;
	private Date updatedDt;
	private char status;
	private String ein;
	private char einVerified;
	public String orgName;
	private String vettingRequestId;

	public Widget() {
	}

	public Widget(String payerid, String widgetexternalid, Date createdDt,
			Date updatedDt, char status, String ein, char einVerified, String orgName, String vettingRequestId) {
		this.payerid = payerid;
		this.widgetexternalid = widgetexternalid;
		this.updatedDt = updatedDt;
		this.status = status;
		this.ein = ein;
		this.einVerified = einVerified;
		this.orgName = orgName;
		this.vettingRequestId = vettingRequestId;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getPayerid() {
		return this.payerid;
	}

	public void setPayerid(String payerid) {
		this.payerid = payerid;
	}

	public String getWidgetexternalid() {
		return this.widgetexternalid;
	}

	public void setWidgetexternalid(String widgetexternalid) {
		this.widgetexternalid = widgetexternalid;
	}

	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getEin() {
		return ein;
	}

	public void setEin(String ein) {
		this.ein = ein;
	}

	public char getEinVerified() {
		return einVerified;
	}

	public void setEinVerified(char einVerified) {
		this.einVerified = einVerified;
	}
	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public String getVettingRequestId() {
		return vettingRequestId;
	}

	public void setVettingRequestId(String vettingRequestId) {
		this.vettingRequestId = vettingRequestId;
	}

	@Override
	public String toString() {
		return "Widget [id=" + id + ", payerid=" + payerid
				+ ", widgetexternalid=" + widgetexternalid + ", updatedDt="
				+ updatedDt + ", status=" + status + ", ein=" + ein
				+ ", einVerified=" + einVerified + ", orgName=" + orgName
				+ ", vettingRequestId=" + vettingRequestId + "]";
	}

}
