package com.paypal.donation.models;

// Generated Dec 9, 2011 10:53:44 AM by Hibernate Tools 3.4.0.CR1

/**
 * Widgetui generated by hbm2java
 */
public class Widgetui implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private long id;
	private long widgetid;
	private String payerid;
	private Character themetype;
	private String themevalue;
	private String title;
	private String titlecolor;
	private String coverimageurl;
	private long goal;
	private int goalcurrency;
	private String goalprogbcolor;
	private String cause;
	private String weburl;
	private String contribamts;

	public Widgetui() {
	}

	public Widgetui(int widgetid, String payerid, int goal, int goalcurrency) {
		this.widgetid = widgetid;
		this.payerid = payerid;
		this.goal = goal;
		this.goalcurrency = goalcurrency;
	}

	public Widgetui(int widgetid, String payerid, Character themetype,
			String themevalue, String title, String titlecolor,
			String coverimageurl, int goal, int goalcurrency,
			String goalprogbcolor, String cause, String weburl,
			String contribamts) {
		this.widgetid = widgetid;
		this.payerid = payerid;
		this.themetype = themetype;
		this.themevalue = themevalue;
		this.title = title;
		this.titlecolor = titlecolor;
		this.coverimageurl = coverimageurl;
		this.goal = goal;
		this.goalcurrency = goalcurrency;
		this.goalprogbcolor = goalprogbcolor;
		this.cause = cause;
		this.weburl = weburl;
		this.contribamts = contribamts;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getWidgetid() {
		return this.widgetid;
	}

	public void setWidgetid(long widgetid) {
		this.widgetid = widgetid;
	}

	public String getPayerid() {
		return this.payerid;
	}

	public void setPayerid(String payerid) {
		this.payerid = payerid;
	}

	public Character getThemetype() {
		return this.themetype;
	}

	public void setThemetype(Character themetype) {
		this.themetype = themetype;
	}

	public String getThemevalue() {
		return this.themevalue;
	}

	public void setThemevalue(String themevalue) {
		this.themevalue = themevalue;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitlecolor() {
		return this.titlecolor;
	}

	public void setTitlecolor(String titlecolor) {
		this.titlecolor = titlecolor;
	}

	public String getCoverimageurl() {
		return this.coverimageurl;
	}

	public void setCoverimageurl(String coverimageurl) {
		this.coverimageurl = coverimageurl;
	}

	public long getGoal() {
		return this.goal;
	}

	public void setGoal(long goal) {
		this.goal = goal;
	}

	public int getGoalcurrency() {
		return this.goalcurrency;
	}

	public void setGoalcurrency(int goalcurrency) {
		this.goalcurrency = goalcurrency;
	}

	public String getGoalprogbcolor() {
		return this.goalprogbcolor;
	}

	public void setGoalprogbcolor(String goalprogbcolor) {
		this.goalprogbcolor = goalprogbcolor;
	}

	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	public String getWeburl() {
		return this.weburl;
	}

	public void setWeburl(String weburl) {
		this.weburl = weburl;
	}

	public String getContribamts() {
		return this.contribamts;
	}

	public void setContribamts(String contribamts) {
		this.contribamts = contribamts;
	}

}
